package com.zanini.snowwallet.ui.presentation

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.*
import androidx.compose.material.icons.filled.*
import androidx.compose.ui.graphics.vector.ImageVector

object IconesDisponiveis {
    /**
     * Lista curada com ~150 ícones essenciais para evitar peso excessivo.
     * Cobre Finanças, Casa, Transporte, Alimentação, Saúde, Lazer e UI Geral.
     */
    val icones: Map<String, ImageVector> = mapOf(
        "AcUnit" to Icons.Default.AcUnit,
        "AccessTime" to Icons.Default.AccessTime,
        "AccountBalance" to Icons.Default.AccountBalance,
        "AccountBalanceWallet" to Icons.Default.AccountBalanceWallet,
        "AccountBox" to Icons.Default.AccountBox,
        "AccountCircle" to Icons.Default.AccountCircle,
        "Add" to Icons.Default.Add,
        "AddBusiness" to Icons.Default.AddBusiness,
        "AddCard" to Icons.Default.AddCard,
        "AddCircle" to Icons.Default.AddCircle,
        "AddShoppingCart" to Icons.Default.AddShoppingCart,
        "AirplaneTicket" to Icons.Default.AirplaneTicket,
        "AirportShuttle" to Icons.Default.AirportShuttle,
        "Alarm" to Icons.Default.Alarm,
        "Announcement" to Icons.AutoMirrored.Filled.Announcement,
        "Apartment" to Icons.Default.Apartment,
        "Apps" to Icons.Default.Apps,
        "ArrowBack" to Icons.AutoMirrored.Filled.ArrowBack,
        "ArrowDownward" to Icons.Default.ArrowDownward,
        "ArrowForward" to Icons.AutoMirrored.Filled.ArrowForward,
        "ArrowUpward" to Icons.Default.ArrowUpward,
        "Assignment" to Icons.Default.Assignment,
        "AttachFile" to Icons.Default.AttachFile,
        "AttachMoney" to Icons.Default.AttachMoney,
        "AutoAwesome" to Icons.Default.AutoAwesome,
        "Backpack" to Icons.Default.Backpack,
        "Backup" to Icons.Default.Backup,
        "Bathtub" to Icons.Default.Bathtub,
        "BeachAccess" to Icons.Default.BeachAccess,
        "Bed" to Icons.Default.Bed,
        "BikeScooter" to Icons.Default.BikeScooter,
        "Bolt" to Icons.Default.Bolt,
        "Book" to Icons.Default.Book,
        "Bookmark" to Icons.Default.Bookmark,
        "Brush" to Icons.Default.Brush,
        "Build" to Icons.Default.Build,
        "Business" to Icons.Default.Business,
        "BusinessCenter" to Icons.Default.BusinessCenter,
        "Cake" to Icons.Default.Cake,
        "Calculate" to Icons.Default.Calculate,
        "CalendarToday" to Icons.Default.CalendarToday,
        "Call" to Icons.Default.Call,
        "CameraAlt" to Icons.Default.CameraAlt,
        "Campaign" to Icons.Default.Campaign,
        "Cancel" to Icons.Default.Cancel,
        "CarRepair" to Icons.Default.CarRepair,
        "CardGiftcard" to Icons.Default.CardGiftcard,
        "CardMembership" to Icons.Default.CardMembership,
        "CardTravel" to Icons.Default.CardTravel,
        "Category" to Icons.Default.Category,
        "Celebration" to Icons.Default.Celebration,
        "Chair" to Icons.Default.Chair,
        "Chat" to Icons.Default.Chat,
        "Check" to Icons.Default.Check,
        "CheckCircle" to Icons.Default.CheckCircle,
        "Checkroom" to Icons.Default.Checkroom,
        "ChildCare" to Icons.Default.ChildCare,
        "Circle" to Icons.Default.Circle,
        "CleaningServices" to Icons.Default.CleaningServices,
        "Close" to Icons.Default.Close,
        "Cloud" to Icons.Default.Cloud,
        "Code" to Icons.Default.Code,
        "Coffee" to Icons.Default.Coffee,
        "Commute" to Icons.Default.Commute,
        "Computer" to Icons.Default.Computer,
        "Construction" to Icons.Default.Construction,
        "ContentCut" to Icons.Default.ContentCut,
        "ContentPaste" to Icons.Default.ContentPaste,
        "CreditCard" to Icons.Default.CreditCard,
        "CreditScore" to Icons.Default.CreditScore,
        "CurrencyBitcoin" to Icons.Default.CurrencyBitcoin,
        "CurrencyExchange" to Icons.Default.CurrencyExchange,
        "DarkMode" to Icons.Default.DarkMode,
        "Dashboard" to Icons.Default.Dashboard,
        "Delete" to Icons.Default.Delete,
        "DeliveryDining" to Icons.Default.DeliveryDining,
        "Devices" to Icons.Default.Devices,
        "Diamond" to Icons.Default.Diamond,
        "DirectionsBike" to Icons.Default.DirectionsBike,
        "DirectionsBus" to Icons.Default.DirectionsBus,
        "DirectionsCar" to Icons.Default.DirectionsCar,
        "DirectionsRun" to Icons.Default.DirectionsRun,
        "Discount" to Icons.Default.Discount,
        "Done" to Icons.Default.Done,
        "DoneAll" to Icons.Default.DoneAll,
        "Download" to Icons.Default.Download,
        "Edit" to Icons.Default.Edit,
        "EditNote" to Icons.Default.EditNote,
        "ElectricBolt" to Icons.Default.ElectricBolt,
        "Email" to Icons.Default.Email,
        "EmojiEvents" to Icons.Default.EmojiEvents,
        "EmojiFoodBeverage" to Icons.Default.EmojiFoodBeverage,
        "EmojiObjects" to Icons.Default.EmojiObjects,
        "Error" to Icons.Default.Error,
        "Euro" to Icons.Default.Euro,
        "Event" to Icons.Default.Event,
        "ExitToApp" to Icons.AutoMirrored.Filled.ExitToApp,
        "Face" to Icons.Default.Face,
        "Fastfood" to Icons.Default.Fastfood,
        "Favorite" to Icons.Default.Favorite,
        "FavoriteBorder" to Icons.Default.FavoriteBorder,
        "FileDownload" to Icons.Default.FileDownload,
        "FileUpload" to Icons.Default.FileUpload,
        "FilterAlt" to Icons.Default.FilterAlt,
        "Fingerprint" to Icons.Default.Fingerprint,
        "FitnessCenter" to Icons.Default.FitnessCenter,
        "Flag" to Icons.Default.Flag,
        "Flight" to Icons.Default.Flight,
        "Folder" to Icons.Default.Folder,
        "Forest" to Icons.Default.Forest,
        "FormatListBulleted" to Icons.AutoMirrored.Filled.List,
        "Gavel" to Icons.Default.Gavel,
        "Grade" to Icons.Default.Grade,
        "Group" to Icons.Default.Group,
        "Groups" to Icons.Default.Groups,
        "Handyman" to Icons.Default.Handyman,
        "Headphones" to Icons.Default.Headphones,
        "HealthAndSafety" to Icons.Default.HealthAndSafety,
        "Help" to Icons.AutoMirrored.Filled.Help,
        "History" to Icons.Default.History,
        "Home" to Icons.Default.Home,
        "HomeRepairService" to Icons.Default.HomeRepairService,
        "Hotel" to Icons.Default.Hotel,
        "Icecream" to Icons.Default.Icecream,
        "Image" to Icons.Default.Image,
        "Info" to Icons.Default.Info,
        "Inventory" to Icons.Default.Inventory,
        "Key" to Icons.Default.Key,
        "Keyboard" to Icons.Default.Keyboard,
        "Kitchen" to Icons.Default.Kitchen,
        "Label" to Icons.AutoMirrored.Filled.Label,
        "Language" to Icons.Default.Language,
        "Laptop" to Icons.Default.Laptop,
        "Layers" to Icons.Default.Layers,
        "LightMode" to Icons.Default.LightMode,
        "Lightbulb" to Icons.Default.Lightbulb,
        "List" to Icons.AutoMirrored.Filled.List,
        "LocalBar" to Icons.Default.LocalBar,
        "LocalCafe" to Icons.Default.LocalCafe,
        "LocalDining" to Icons.Default.LocalDining,
        "LocalGasStation" to Icons.Default.LocalGasStation,
        "LocalGroceryStore" to Icons.Default.LocalGroceryStore,
        "LocalHospital" to Icons.Default.LocalHospital,
        "LocalLaundryService" to Icons.Default.LocalLaundryService,
        "LocalMall" to Icons.Default.LocalMall,
        "LocalOffer" to Icons.Default.LocalOffer,
        "LocalParking" to Icons.Default.LocalParking,
        "LocalPharmacy" to Icons.Default.LocalPharmacy,
        "LocalPizza" to Icons.Default.LocalPizza,
        "LocalShipping" to Icons.Default.LocalShipping,
        "LocalTaxi" to Icons.Default.LocalTaxi,
        "LocationOn" to Icons.Default.LocationOn,
        "Lock" to Icons.Default.Lock,
        "Login" to Icons.AutoMirrored.Filled.Login,
        "Logout" to Icons.AutoMirrored.Filled.Logout,
        "Mail" to Icons.Default.Mail,
        "Map" to Icons.Default.Map,
        "MedicalServices" to Icons.Default.MedicalServices,
        "Menu" to Icons.Default.Menu,
        "Mic" to Icons.Default.Mic,
        "Money" to Icons.Default.Money,
        "MoneyOff" to Icons.Default.MoneyOff,
        "Monitor" to Icons.Default.Monitor,
        "MoreHoriz" to Icons.Default.MoreHoriz,
        "MoreVert" to Icons.Default.MoreVert,
        "Motorcycle" to Icons.Default.Motorcycle,
        "Movie" to Icons.Default.Movie,
        "MusicNote" to Icons.Default.MusicNote,
        "Navigation" to Icons.Default.Navigation,
        "Notifications" to Icons.Default.Notifications,
        "Paid" to Icons.Default.Paid,
        "Palette" to Icons.Default.Palette,
        "Park" to Icons.Default.Park,
        "Password" to Icons.Default.Password,
        "Payment" to Icons.Default.Payment,
        "PedalBike" to Icons.Default.PedalBike,
        "People" to Icons.Default.People,
        "Person" to Icons.Default.Person,
        "Pets" to Icons.Default.Pets,
        "Phone" to Icons.Default.Phone,
        "PhotoCamera" to Icons.Default.PhotoCamera,
        "PieChart" to Icons.Default.PieChart,
        "Place" to Icons.Default.Place,
        "Pool" to Icons.Default.Pool,
        "Power" to Icons.Default.Power,
        "Print" to Icons.Default.Print,
        "PriorityHigh" to Icons.Default.PriorityHigh,
        "Public" to Icons.Default.Public,
        "QrCode" to Icons.Default.QrCode,
        "QuestionMark" to Icons.Default.QuestionMark,
        "Receipt" to Icons.Default.Receipt,
        "ReceiptLong" to Icons.Default.ReceiptLong,
        "Refresh" to Icons.Default.Refresh,
        "Remove" to Icons.Default.Remove,
        "Restaurant" to Icons.Default.Restaurant,
        "Rocket" to Icons.Default.Rocket,
        "Room" to Icons.Default.Room,
        "Router" to Icons.Default.Router,
        "Save" to Icons.Default.Save,
        "Savings" to Icons.Default.Savings,
        "School" to Icons.Default.School,
        "Search" to Icons.Default.Search,
        "Security" to Icons.Default.Security,
        "Sell" to Icons.Default.Sell,
        "Send" to Icons.AutoMirrored.Filled.Send,
        "Settings" to Icons.Default.Settings,
        "Share" to Icons.Default.Share,
        "Shield" to Icons.Default.Shield,
        "ShoppingBag" to Icons.Default.ShoppingBag,
        "ShoppingCart" to Icons.Default.ShoppingCart,
        "Smartphone" to Icons.Default.Smartphone,
        "Sort" to Icons.AutoMirrored.Filled.Sort,
        "Spa" to Icons.Default.Spa,
        "Speaker" to Icons.Default.Speaker,
        "Speed" to Icons.Default.Speed,
        "SportsEsports" to Icons.Default.SportsEsports,
        "SportsSoccer" to Icons.Default.SportsSoccer,
        "Star" to Icons.Default.Star,
        "Store" to Icons.Default.Store,
        "SupportAgent" to Icons.Default.SupportAgent,
        "Sync" to Icons.Default.Sync,
        "Tag" to Icons.Default.Tag,
        "ThumbUp" to Icons.Default.ThumbUp,
        "Timeline" to Icons.Default.Timeline,
        "Timer" to Icons.Default.Timer,
        "Today" to Icons.Default.Today,
        "Train" to Icons.Default.Train,
        "Tram" to Icons.Default.Tram,
        "Translate" to Icons.Default.Translate,
        "TrendingDown" to Icons.AutoMirrored.Filled.TrendingDown,
        "TrendingUp" to Icons.AutoMirrored.Filled.TrendingUp,
        "Tv" to Icons.Default.Tv,
        "Umbrella" to Icons.Default.Umbrella,
        "Update" to Icons.Default.Update,
        "Upload" to Icons.Default.Upload,
        "Verified" to Icons.Default.Verified,
        "VideoCall" to Icons.Default.VideoCall,
        "Visibility" to Icons.Default.Visibility,
        "VisibilityOff" to Icons.Default.VisibilityOff,
        "VolumeUp" to Icons.AutoMirrored.Filled.VolumeUp,
        "Wallet" to Icons.Default.Wallet,
        "Warning" to Icons.Default.Warning,
        "Watch" to Icons.Default.Watch,
        "WaterDrop" to Icons.Default.WaterDrop,
        "WavingHand" to Icons.Default.WavingHand,
        "WbSunny" to Icons.Default.WbSunny,
        "Web" to Icons.Default.Web,
        "Wifi" to Icons.Default.Wifi,
        "Work" to Icons.Default.Work,
        "WorkOutline" to Icons.Default.WorkOutline,
        "ZoomIn" to Icons.Default.ZoomIn
    )

    /**
     * Função SEGURA para recuperar um ícone pelo nome.
     * Retorna Icons.Default.Category se não encontrar, evitando crash.
     */
    fun getIcone(nome: String?): ImageVector {
        if (nome.isNullOrBlank()) return Icons.Default.Category
        return icones[nome] ?: Icons.Default.Category
    }

    /**
     * Retorna lista de nomes ordenada para Dropdowns.
     */
    fun getNomesOrdenados(): List<String> {
        return icones.keys.toList().sorted()
    }
}